
package kantin;

import java.awt.Component;
import modul.koneksi;
import java.sql.*;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

public class dasboard_trend extends javax.swing.JFrame {
    public static Dimension ukuran;
    private DefaultTableModel model = null; // untuk model tabelnya supaya dengan sesuai keinginan kita
    private PreparedStatement stat; // supaya dapat mengirimkan query atau menmpung code sql
    private ResultSet rs; //return value yang didapat apabila kita menjalankan SQL statement
    koneksi k = new koneksi(); //panggil class koneksi

    public dasboard_trend() {
        initComponents();
        k.connect();
        refreshTable();
        ukuran = Toolkit.getDefaultToolkit().getScreenSize();
        setExtendedState(JFrame.MAXIMIZED_BOTH); // Untuk membuat frame full screen
        jPanel1.setPreferredSize(ukuran); // Mengatur ukuran panel sesuai layar
        
    }
    
private void settablerender() {
     //Inner class untuk  rendering sel tabel
    class customrender extends DefaultTableCellRenderer {

        //Override metode untuk menyesuaikan tampilan sel tabel
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            // Memeriksa apakah nilai adalah array byte (gambar)
           if (value instanceof byte[]) { //memeriksa apakah objek (value) adalah instance dari tipe kelas
                // Mengubah data byte array menjadi ImageIcon
                byte[] imageData = (byte[]) value; //value menjadi tipe byte[] dan menyimpannya dalam variabel imageData.
               ImageIcon icon = new ImageIcon(imageData);
               
               // Memanggil/Membuat label untuk menampilkan gambar
                JLabel label = new JLabel(icon);
               
                // Mengatur tata letak gambar menjadi tengah
               label.setHorizontalAlignment(JLabel.CENTER);
                
               // Mengembalikan label untuk ditampilkan di sel tabel
                return label; //sama seperti soutprln tapi return itu non void
            } else {
               //memanggil metode getTableCellRendererComponent() dari kelas induk (superclass) yang diperluas oleh kelas saat ini (customrender).
                // Jika nilai sel bukan array byte (gambar), kembalikan default renderer
                return super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
           }
        }

   }
   // Mengatur renderer khusus untuk kolom gambar di tabel
    jTable_Menutrend.getColumnModel().getColumn(4).setCellRenderer(new customrender());
}
    
    public void refreshTable (){ // fungsinya untuk membuat komponen baris dan colom di table desaign
        model = new DefaultTableModel(); // setting modelnya
        model.addColumn("ID Masakan");
        model.addColumn("Nama Masakan");
        model.addColumn("Harga");
        model.addColumn("Status Masakan");
        model.addColumn("Gambar");
        
        jTable_Menutrend.setModel(model); // memasukan komponen table ke tabel GUI
        
        try { // setiap mengambil data di localhost atau sql dengan menggunakan try
            this.stat = k.getCon().prepareStatement("select * from masakan"); // untuk mengeksekusi syntax sql
            this.rs = this.stat.executeQuery(); //mengambil data localhost(sql)ke dalam tabel GUI
            while (rs.next()) {// karena akan banyak user, menggunakan perulangan
                Object[] data = { // disatu baris didefinisikan dengan array
                    //data yang ditampung di rs kemudian kita masukan di setiap kolom
                  rs.getString(1),
                  rs.getString(2),
                  rs.getInt(3),
                  rs.getString(4),
                  rs.getBytes(5)
                };
                model.addRow(data); //kemudiaan kita masukan di model di setiap baris
                settablerender();
            }
            
        } catch (Exception e) { // untuk memberi tau  jika ada eroor
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_Menutrend = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel_picture = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuBar_home = new javax.swing.JMenu();
        jMenuBar_profil = new javax.swing.JMenu();
        jMenuBar_trend = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setPreferredSize(new java.awt.Dimension(1500, 777));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("SELAMAT DATANG DI MASAKAN KANTIN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, -1));

        jTable_Menutrend.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_Menutrend.setMinimumSize(new java.awt.Dimension(100, 400));
        jTable_Menutrend.setRowHeight(90);
        jTable_Menutrend.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_MenutrendMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_Menutrend);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 1315, 290));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel_picture.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel_picture, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel_picture, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 90, 330, 290));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/bg_all.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jMenuBar1.setBackground(new java.awt.Color(204, 4, 255));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(163, 50));
        jMenuBar1.setRequestFocusEnabled(false);
        jMenuBar1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jMenuBar1ComponentResized(evt);
            }
        });

        jMenuBar_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/button home.png"))); // NOI18N
        jMenuBar_home.setText("HOME");
        jMenuBar_home.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jMenuBar_home.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jMenuBar_homeMouseMoved(evt);
            }
        });
        jMenuBar_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuBar_homeMouseClicked(evt);
            }
        });
        jMenuBar_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuBar_homeActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenuBar_home);

        jMenuBar_profil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/dashboard profil.png"))); // NOI18N
        jMenuBar_profil.setText("TENTANG");
        jMenuBar_profil.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jMenuBar_profil.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jMenuBar_profilMouseMoved(evt);
            }
        });
        jMenuBar_profil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuBar_profilMouseClicked(evt);
            }
        });
        jMenuBar_profil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuBar_profilActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenuBar_profil);

        jMenuBar_trend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/dashboard trend.png"))); // NOI18N
        jMenuBar_trend.setText("MASAKAN");
        jMenuBar_trend.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jMenuBar1.add(jMenuBar_trend);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1566, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuBar1ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jMenuBar1ComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuBar1ComponentResized

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void jMenuBar_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuBar_homeActionPerformed
        
    }//GEN-LAST:event_jMenuBar_homeActionPerformed

    private void jMenuBar_profilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuBar_profilActionPerformed
        
    }//GEN-LAST:event_jMenuBar_profilActionPerformed

    private void jMenuBar_homeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuBar_homeMouseMoved
        
    }//GEN-LAST:event_jMenuBar_homeMouseMoved

    private void jMenuBar_profilMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuBar_profilMouseMoved
        
    }//GEN-LAST:event_jMenuBar_profilMouseMoved

    private void jMenuBar_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuBar_homeMouseClicked
        dasboard home = new dasboard();
        home.setVisible(true);
        this.setVisible(false);
        this.dispose();
    
    // Membuat instance baru dari dasboard dan menampilkannya
    dasboard dashboard = new dasboard();
    dashboard.setVisible(true);
    
    // Menampilkan dialog pop-up untuk memilih jenis pengguna
    String[] options = {"Customer", "Karyawan", "Administrator"};
    int choice = JOptionPane.showOptionDialog(dashboard, "Pilih jenis pengguna:", "Jenis Pengguna", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
    
    // Menentukan jenis pengguna berdasarkan pilihan pengguna
    String jenisPengguna;
    if (choice >= 0 && choice < options.length) {
        jenisPengguna = options[choice]; //akan mengeksekisi jenis pengguna berdasarkan opsi pilihan pada metod cekpengguna()
    } else {
        // Default jika pengguna tidak memilih atau menutup dialog
        jenisPengguna = "Guest";
    }
    
    // Memanggil metode cekPengguna() dengan parameter yang sesuai
    dashboard.cekPengguna(jenisPengguna);
    }//GEN-LAST:event_jMenuBar_homeMouseClicked

    private void jMenuBar_profilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuBar_profilMouseClicked
        dasboard_profil prof = new dasboard_profil();
        prof.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuBar_profilMouseClicked

    private void jTable_MenutrendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_MenutrendMouseClicked
        int selectedRow = jTable_Menutrend.getSelectedRow(); // Mendapatkan indeks baris yang dipilih. Mengembalikan -1 jika tidak ada baris yang dipilih
        //karena di Java Swing, metode getSelectedRow() dari kelas JTable mengembalikan nilai -1  ketika tidak ada baris yang dipilih
        if (selectedRow != -1) { // Memastikan ada baris yang dipilih
        Object imageData = model.getValueAt(selectedRow, 4); // Mengambil data gambar dari kolom ke-4 (indeks 4)
        if (imageData instanceof byte[]) { // Memastikan data adalah array byte (gambar)
            byte[] imageBytes = (byte[]) imageData; //value menjadi tipe byte[] dan menyimpannya dalam variabel imageData.
            ImageIcon icon = new ImageIcon(imageBytes);
            
            // Mengatur gambar agar sesuai dengan ukuran jLabel_picture
            Image img = icon.getImage();
            Image scaledImg = img.getScaledInstance(jLabel_picture.getWidth(), jLabel_picture.getHeight(), Image.SCALE_SMOOTH); //skala img
            ImageIcon scaledIcon = new ImageIcon(scaledImg);
            
            jLabel_picture.setIcon(scaledIcon); // Mengatur ikon yang telah diskalakan pada jLabel_picture
        } else {
            jLabel_picture.setText("Tidak ada gambar"); // Tampilkan pesan teks
        }
    }
    }//GEN-LAST:event_jTable_MenutrendMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dasboard_trend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dasboard_trend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dasboard_trend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dasboard_trend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dasboard_trend().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_picture;
    public static javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuBar_home;
    private javax.swing.JMenu jMenuBar_profil;
    private javax.swing.JMenu jMenuBar_trend;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_Menutrend;
    // End of variables declaration//GEN-END:variables
}
